---
concurrency:
  cancel-in-progress: true
  group: documentation-${{ github.ref }}
jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Restore pip cache
        uses: actions/cache@v5
        with:
          key: >-
            pip-${{ github.job }}-${{
            hashFiles('.github/workflows/documentation.yml') }}
          path: ~/.cache/pip
          restore-keys: |
            pip-${{ github.job }}-
      - name: Install tools
        run: |
          npm install -g markdownlint-cli
          pip install \
            assert-no-inline-directives \
            assert-no-linter-config-files
      - name: Assert no inline markdownlint disables
        run: >-
          assert-no-inline-directives
          --tools markdownlint
          --verbose
          ${{ github.workspace }}/**/*
      - name: Assert no markdownlint config files
        run: >-
          assert-no-linter-config-files
          --linters markdownlint
          --verbose
          ${{ github.workspace }}
      - name: Lint Markdown
        run: markdownlint '**/*.md' '.claude/**/*.md' --disable MD013
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Restore pip cache
        uses: actions/cache@v5
        with:
          key: >-
            pip-${{ github.job }}-${{
            hashFiles('.github/workflows/documentation.yml') }}
          path: ~/.cache/pip
          restore-keys: |
            pip-${{ github.job }}-
      - name: Install tools
        run: >-
          pip install
          assert-no-inline-directives
          assert-no-linter-config-files
          yamllint
      - name: Assert no inline yamllint disables
        run: >-
          assert-no-inline-directives
          --tools yamllint
          --verbose
          .github/workflows/documentation.yml
      - name: Lint YAML
        run: |
          EMPTY='empty-lines: {max: 0, max-start: 0, max-end: 1}'
          KEY='key-ordering: enable'
          LL='line-length: disable'
          NL='new-line-at-end-of-file: enable'
          TR='truthy: {allowed-values: ["true", "false", "on"]}'
          RULES="$EMPTY, $KEY, $LL, $NL, $TR"
          yamllint --strict \
            --config-data \
            "{extends: default, rules: {$RULES}}" \
            .github/workflows/documentation.yml
name: documentation
on:
  push:
    branches: [main]
    paths:
      - '**/*.md'
      - .claude/**/*.md
      - .github/workflows/documentation.yml
  workflow_dispatch: {}
